name: geobase
description: Application to manage geografical information locally on your device.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '^3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  file_picker: ^9.0.2
  flash: ^3.1.1
  flutter_bloc: ^8.1.1
  flutter_image: ^4.1.4
  flutter_map: ^8.1.1
  flutter_lyform: ^0.15.0
  flutter_riverpod: ^2.0.2
  flutter_form_bloc: ^0.31.0
  flutter_iconpicker: ^3.2.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.7.0
  latlong2: ^0.9.1
  location: ^8.0.0
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  rxdart: ^0.27.5
  beamer: ^1.5.3
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.0.11
  sqfentity: ^2.3.0+5
  sqfentity_gen: ^2.3.0+4
  reflectable: ^4.0.12
  image_picker: ^1.1.2
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  build_verify: ^3.0.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.0-0.0.dev
  injectable_generator: ^2.6.2
  json_serializable: ^6.5.3
  # customization
  # flutter_native_splash
  # flutter_launcher_icons
  # code checks

flutter:
  uses-material-design: true
  assets:
    # icons
    - assets/icons/

  fonts:
    - family: Aller
      fonts:
        - asset: assets/fonts/Aller_Std_Rg.ttf
        - asset: assets/fonts/Aller_Std_It.ttf
          style: italic
        - asset: assets/fonts/Aller_Std_Bd.ttf
          weight: 700
