// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_bool_field_render.dart'
    as prefix1;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_date_field_render.dart'
    as prefix2;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_datetime_field_render.dart'
    as prefix3;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_double_field_render.dart'
    as prefix4;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_int_field_render.dart'
    as prefix5;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_qr_field_render.dart'
    as prefix6;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/base_string_field_render.dart'
    as prefix7;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/field_render_class.dart'
    as prefix8;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/form_field_render.dart'
    as prefix9;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/media_audio_field_render.dart'
    as prefix10;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/media_field_render.dart'
    as prefix11;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/media_file_field_render.dart'
    as prefix12;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/media_image_field_render.dart'
    as prefix13;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/media_video_field_render.dart'
    as prefix14;
import 'package:geobase/src/presentation/core/widgets/render_classes/field_render_classes/staticselection_field_render.dart'
    as prefix15;
import 'package:geobase/src/presentation/core/widgets/render_classes/reflect.dart'
    as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FieldRenderReflectable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'BaseBoolFieldRender',
            r'.BaseBoolFieldRender',
            134217735,
            0,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.BaseBoolFieldRender() : null},
            -1,
            0,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseDateFieldRender',
            r'.BaseDateFieldRender',
            134217735,
            1,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.BaseDateFieldRender() : null},
            -1,
            1,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseDateTimeFieldRender',
            r'.BaseDateTimeFieldRender',
            134217735,
            2,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix3.BaseDateTimeFieldRender() : null
            },
            -1,
            2,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseDoubleFieldRender',
            r'.BaseDoubleFieldRender',
            134217735,
            3,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix4.BaseDoubleFieldRender() : null},
            -1,
            3,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseIntFieldRender',
            r'.BaseIntFieldRender',
            134217735,
            4,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix5.BaseIntFieldRender() : null},
            -1,
            4,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseQRFieldRender',
            r'.BaseQRFieldRender',
            134217735,
            5,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix6.BaseQRFieldRender() : null},
            -1,
            5,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'BaseStringFieldRender',
            r'.BaseStringFieldRender',
            134217735,
            6,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix7.BaseStringFieldRender() : null},
            -1,
            6,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'IFieldRenderClass',
            r'.IFieldRenderClass',
            134218247,
            7,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            7,
            const <int>[],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'FormFieldRender',
            r'.FormFieldRender',
            134217735,
            8,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix9.FormFieldRender() : null},
            -1,
            8,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'MediaAudioFieldRender',
            r'.MediaAudioFieldRender',
            134217735,
            9,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix10.MediaAudioFieldRender() : null
            },
            -1,
            9,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'MediaFieldRender',
            r'.MediaFieldRender',
            134217735,
            10,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix11.MediaFieldRender() : null},
            -1,
            10,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'MediaFileFieldRender',
            r'.MediaFileFieldRender',
            134217735,
            11,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix12.MediaFileFieldRender() : null},
            -1,
            11,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'MediaImageFieldRender',
            r'.MediaImageFieldRender',
            134217735,
            12,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix13.MediaImageFieldRender() : null
            },
            -1,
            12,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'MediaVideoFieldRender',
            r'.MediaVideoFieldRender',
            134217735,
            13,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => () => b ? prefix14.MediaVideoFieldRender() : null
            },
            -1,
            13,
            const <int>[7],
            null,
            {}),
        r.NonGenericClassMirrorImpl(
            r'StaticSelectionFieldRender',
            r'.StaticSelectionFieldRender',
            134217735,
            14,
            const prefix0.FieldRenderReflectable(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  () => b ? prefix15.StaticSelectionFieldRender() : null
            },
            -1,
            14,
            const <int>[7],
            null,
            {})
      ],
      null,
      null,
      <Type>[
        prefix1.BaseBoolFieldRender,
        prefix2.BaseDateFieldRender,
        prefix3.BaseDateTimeFieldRender,
        prefix4.BaseDoubleFieldRender,
        prefix5.BaseIntFieldRender,
        prefix6.BaseQRFieldRender,
        prefix7.BaseStringFieldRender,
        prefix8.IFieldRenderClass,
        prefix9.FormFieldRender,
        prefix10.MediaAudioFieldRender,
        prefix11.MediaFieldRender,
        prefix12.MediaFileFieldRender,
        prefix13.MediaImageFieldRender,
        prefix14.MediaVideoFieldRender,
        prefix15.StaticSelectionFieldRender
      ],
      15,
      {},
      {},
      null,
      [
        const [0, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
